// Package source provides bounded, read-only access to configured sources.
//
// The package deliberately exposes metadata and bounded previews instead of
// retaining complete source contents. A source is untrusted input: callers
// must treat discovery failures and limits as part of the result, not as
// evidence that an item does not exist.
package source

import (
	"errors"
	"fmt"
	"math"
	"path/filepath"
	"time"
)

const (
	// DefaultMaxFiles bounds the number of regular files visited by a default
	// configuration. Callers can choose a smaller or larger explicit limit.
	DefaultMaxFiles = 100_000

	// DefaultMaxBytes bounds the total regular-file bytes considered by a
	// default configuration.
	DefaultMaxBytes int64 = 1 << 30

	// DefaultMaxFileBytes bounds one regular file in a default configuration.
	DefaultMaxFileBytes int64 = 256 << 20

	// DefaultMaxArchiveMembers bounds members inspected in a ZIP/CAR archive.
	DefaultMaxArchiveMembers = 10_000

	// DefaultMaxArchiveBytes bounds the declared expanded bytes in an archive.
	DefaultMaxArchiveBytes int64 = 1 << 30

	// DefaultMaxArchiveMemberBytes bounds one declared archive member.
	DefaultMaxArchiveMemberBytes int64 = 256 << 20

	// DefaultMaxExpansionRatio limits declared expanded bytes relative to
	// compressed bytes. It is intentionally finite to reject ZIP bombs.
	DefaultMaxExpansionRatio = 1_000.0

	// DefaultMaxProbeBytes is enough to classify common text and binary files
	// without retaining a complete source file in memory.
	DefaultMaxProbeBytes int64 = 8 << 10

	// DefaultMaxExtractionBytes bounds an explicitly requested text preview.
	DefaultMaxExtractionBytes int64 = 1 << 20
)

var (
	// ErrInvalidRoot identifies a missing, non-directory, or invalid source
	// root.
	ErrInvalidRoot = errors.New("source: invalid root")
	// ErrPathTraversal identifies a path that escapes the configured root.
	ErrPathTraversal = errors.New("source: path traversal")
	// ErrSymlink identifies a symbolic link, which is not followed by default.
	ErrSymlink = errors.New("source: symbolic link is not allowed")
	// ErrSpecialFile identifies a device, socket, pipe, or other non-regular
	// filesystem entry.
	ErrSpecialFile = errors.New("source: special file is not allowed")
	// ErrLimitExceeded identifies a configured resource limit.
	ErrLimitExceeded = errors.New("source: resource limit exceeded")
	// ErrUnsupported identifies a format or operation not supported by this
	// package.
	ErrUnsupported = errors.New("source: unsupported input")
	// ErrArchivePath identifies a package member with an unsafe path.
	ErrArchivePath = errors.New("source: unsafe archive member path")
	// ErrArchiveEncrypted identifies an encrypted ZIP member. Decryption is
	// intentionally outside this runtime's trust boundary.
	ErrArchiveEncrypted = errors.New("source: encrypted archive member is not supported")
	// ErrBinary identifies an operation that requires textual content.
	ErrBinary = errors.New("source: binary content")
)

// FailureKind classifies a problem without collapsing a partial result into a
// total technical failure.
type FailureKind string

const (
	FailureSecurity    FailureKind = "security"
	FailureLimit       FailureKind = "limit"
	FailureCancelled   FailureKind = "cancelled"
	FailureTechnical   FailureKind = "technical"
	FailureUnsupported FailureKind = "unsupported"
)

// Failure records a problem associated with a source path or archive member.
// Message is safe metadata generated by the runtime; callers must not put raw
// source content in it.
type Failure struct {
	Kind    FailureKind `json:"kind"`
	Path    string      `json:"path,omitempty"`
	Code    string      `json:"code"`
	Message string      `json:"message"`
}

func (f Failure) Error() string {
	if f.Path == "" {
		return fmt.Sprintf("%s: %s", f.Code, f.Message)
	}
	return fmt.Sprintf("%s %q: %s", f.Code, f.Path, f.Message)
}

// Classification is the conservative content classification used by the
// generic extractor.
type Classification string

const (
	ClassificationUnknown Classification = "unknown"
	ClassificationText    Classification = "text"
	ClassificationBinary  Classification = "binary"
)

// Format identifies the small set of package formats understood by the
// runtime. A CAR is a ZIP container with a .car extension.
type Format string

const (
	FormatUnknown Format = "unknown"
	FormatZIP     Format = "zip"
	FormatCAR     Format = "car"
)

// Limits controls work performed during discovery and package inspection. A
// zero value uses the package defaults; negative values are rejected.
type Limits struct {
	MaxFiles int `json:"max_files,omitempty"`
	// MaxBytes is the total source-content bytes read by discovery. Hashing
	// and classification share one stream, so a byte is counted once.
	MaxBytes                  int64         `json:"max_bytes,omitempty"`
	MaxFileBytes              int64         `json:"max_file_bytes,omitempty"`
	MaxDuration               time.Duration `json:"max_duration,omitempty"`
	MaxConcurrency            int           `json:"max_concurrency,omitempty"`
	MaxProbeBytes             int64         `json:"max_probe_bytes,omitempty"`
	MaxExtractionBytes        int64         `json:"max_extraction_bytes,omitempty"`
	MaxArchiveMembers         int           `json:"max_archive_members,omitempty"`
	MaxArchiveBytes           int64         `json:"max_archive_bytes,omitempty"`
	MaxArchiveMemberBytes     int64         `json:"max_archive_member_bytes,omitempty"`
	MaxArchiveCompressedBytes int64         `json:"max_archive_compressed_bytes,omitempty"`
	MaxExpansionRatio         float64       `json:"max_expansion_ratio,omitempty"`
}

// DefaultLimits returns a safe finite set of limits.
func DefaultLimits() Limits {
	return Limits{
		MaxFiles:                  DefaultMaxFiles,
		MaxBytes:                  DefaultMaxBytes,
		MaxFileBytes:              DefaultMaxFileBytes,
		MaxConcurrency:            1,
		MaxProbeBytes:             DefaultMaxProbeBytes,
		MaxExtractionBytes:        DefaultMaxExtractionBytes,
		MaxArchiveMembers:         DefaultMaxArchiveMembers,
		MaxArchiveBytes:           DefaultMaxArchiveBytes,
		MaxArchiveMemberBytes:     DefaultMaxArchiveMemberBytes,
		MaxArchiveCompressedBytes: DefaultMaxArchiveBytes,
		MaxExpansionRatio:         DefaultMaxExpansionRatio,
	}
}

func (l Limits) normalized() (Limits, error) {
	defaults := DefaultLimits()
	if l.MaxFiles < 0 || l.MaxBytes < 0 || l.MaxFileBytes < 0 ||
		l.MaxDuration < 0 || l.MaxConcurrency < 0 || l.MaxProbeBytes < 0 ||
		l.MaxExtractionBytes < 0 || l.MaxArchiveMembers < 0 ||
		l.MaxArchiveBytes < 0 || l.MaxArchiveMemberBytes < 0 ||
		l.MaxArchiveCompressedBytes < 0 || l.MaxExpansionRatio < 0 ||
		math.IsNaN(l.MaxExpansionRatio) || math.IsInf(l.MaxExpansionRatio, 0) {
		return Limits{}, fmt.Errorf("%w: negative limit", ErrLimitExceeded)
	}
	if l.MaxFiles == 0 {
		l.MaxFiles = defaults.MaxFiles
	}
	if l.MaxBytes == 0 {
		l.MaxBytes = defaults.MaxBytes
	}
	if l.MaxFileBytes == 0 {
		l.MaxFileBytes = defaults.MaxFileBytes
	}
	if l.MaxConcurrency == 0 {
		l.MaxConcurrency = defaults.MaxConcurrency
	}
	if l.MaxConcurrency > 1024 {
		return Limits{}, fmt.Errorf("%w: concurrency limit is too large", ErrLimitExceeded)
	}
	if l.MaxProbeBytes == 0 {
		l.MaxProbeBytes = defaults.MaxProbeBytes
	}
	if l.MaxExtractionBytes == 0 {
		l.MaxExtractionBytes = defaults.MaxExtractionBytes
	}
	if l.MaxArchiveMembers == 0 {
		l.MaxArchiveMembers = defaults.MaxArchiveMembers
	}
	if l.MaxArchiveBytes == 0 {
		l.MaxArchiveBytes = defaults.MaxArchiveBytes
	}
	if l.MaxArchiveMemberBytes == 0 {
		l.MaxArchiveMemberBytes = defaults.MaxArchiveMemberBytes
	}
	if l.MaxArchiveCompressedBytes == 0 {
		l.MaxArchiveCompressedBytes = defaults.MaxArchiveCompressedBytes
	}
	if l.MaxExpansionRatio == 0 {
		l.MaxExpansionRatio = defaults.MaxExpansionRatio
	}
	return l, nil
}

// Validate checks limits without starting work. Zero values are interpreted
// as the same safe defaults used by discovery.
func (l Limits) Validate() error {
	_, err := l.normalized()
	return err
}

// Config defines a read-only source recorte. Include and exclude patterns use
// slash-separated relative paths and support ** for any number of components.
type Config struct {
	Root              string   `json:"root"`
	Includes          []string `json:"includes,omitempty"`
	Excludes          []string `json:"excludes,omitempty"`
	SensitivePatterns []string `json:"sensitive_patterns,omitempty"`
	IncludeSensitive  bool     `json:"include_sensitive,omitempty"`
	Limits            Limits   `json:"limits"`
}

// Validate checks the root, path patterns, and limits without traversing the
// source contents.
func (c Config) Validate() error {
	_, _, _, err := normalizedConfig(c)
	return err
}

// Artifact is a regular file discovered below a source root. Path is the
// normalized absolute path used internally to open the source; RelativePath
// is the stable, portable identifier for results and citations.
type Artifact struct {
	Path           string         `json:"-"`
	RelativePath   string         `json:"path"`
	Size           int64          `json:"size"`
	SHA256         string         `json:"sha256"`
	Classification Classification `json:"classification"`
	Format         Format         `json:"format,omitempty"`
}

// Exclusion explains why a path was intentionally not analyzed.
type Exclusion struct {
	Path    string `json:"path"`
	Pattern string `json:"pattern,omitempty"`
	Reason  string `json:"reason"`
}

// DiscoveryResult is a partial-safe result. Artifacts completed before a
// cancellation or limit remain available and are sorted by RelativePath.
type DiscoveryResult struct {
	Root            string      `json:"root"`
	Artifacts       []Artifact  `json:"artifacts"`
	Exclusions      []Exclusion `json:"exclusions,omitempty"`
	Failures        []Failure   `json:"failures,omitempty"`
	FilesDiscovered int         `json:"files_discovered"`
	BytesRead       int64       `json:"bytes_read"`
	Limited         bool        `json:"limited"`
	Cancelled       bool        `json:"cancelled"`
	Concurrency     int         `json:"concurrency"`
	DurationNanos   int64       `json:"duration_nanos"`
}

// TextOptions controls explicit, bounded textual extraction. IncludeContent
// defaults to false so callers cannot accidentally put complete source text
// into a result or log.
type TextOptions struct {
	MaxBytes       int64 `json:"max_bytes,omitempty"`
	IncludeContent bool  `json:"include_content,omitempty"`
}

// TextResult contains classification and an optional bounded preview.
type TextResult struct {
	Classification Classification `json:"classification"`
	BytesRead      int64          `json:"bytes_read"`
	Truncated      bool           `json:"truncated"`
	Content        string         `json:"content,omitempty"`
}

// ArchiveOptions controls safe ZIP/CAR inspection. Zero values use the
// archive-related defaults from DefaultLimits.
type ArchiveOptions struct {
	MaxMembers         int
	MaxExpandedBytes   int64
	MaxMemberBytes     int64
	MaxCompressedBytes int64
	MaxExpansionRatio  float64
}

func (o ArchiveOptions) normalized() (ArchiveOptions, error) {
	l, err := (Limits{
		MaxArchiveMembers:         o.MaxMembers,
		MaxArchiveBytes:           o.MaxExpandedBytes,
		MaxArchiveMemberBytes:     o.MaxMemberBytes,
		MaxArchiveCompressedBytes: o.MaxCompressedBytes,
		MaxExpansionRatio:         o.MaxExpansionRatio,
	}).normalized()
	if err != nil {
		return ArchiveOptions{}, err
	}
	return ArchiveOptions{
		MaxMembers:         l.MaxArchiveMembers,
		MaxExpandedBytes:   l.MaxArchiveBytes,
		MaxMemberBytes:     l.MaxArchiveMemberBytes,
		MaxCompressedBytes: l.MaxArchiveCompressedBytes,
		MaxExpansionRatio:  l.MaxExpansionRatio,
	}, nil
}

// Validate checks archive limits without opening an archive.
func (o ArchiveOptions) Validate() error {
	_, err := o.normalized()
	return err
}

// ArchiveMember is metadata for a ZIP/CAR member. Content is never retained
// by InspectArchive.
type ArchiveMember struct {
	Name           string         `json:"name"`
	Size           uint64         `json:"size"`
	CompressedSize uint64         `json:"compressed_size"`
	Method         uint16         `json:"method"`
	Directory      bool           `json:"directory"`
	Classification Classification `json:"classification"`
}

// ArchiveResult describes a package without extracting it to disk.
type ArchiveResult struct {
	Path            string          `json:"path,omitempty"`
	Format          Format          `json:"format"`
	Members         []ArchiveMember `json:"members"`
	ExpandedBytes   uint64          `json:"expanded_bytes"`
	CompressedBytes uint64          `json:"compressed_bytes"`
}

// IsPathWithin reports whether candidate is inside root after lexical
// normalization. It does not follow links; callers must still reject links
// with Lstat/DirEntry.Type before opening a path.
func IsPathWithin(root, candidate string) bool {
	root = filepath.Clean(root)
	candidate = filepath.Clean(candidate)
	rel, err := filepath.Rel(root, candidate)
	if err != nil {
		return false
	}
	return rel != ".." && rel != "" && !isParentPath(rel)
}

func isParentPath(path string) bool {
	return path == ".." || len(path) > 3 && path[:3] == ".."+string(filepath.Separator)
}
