package query

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"strings"

	"github.com/pedrogpaulino/manu/internal/retrieval"
)

const (
	// ContextRetrievalPlanOrdering identifies the stable candidate ordering
	// reserved for the context assembly pipeline.
	ContextRetrievalPlanOrdering = "rank-kind-id-v1"
	// ContextRetrievalPlanAssemblyVersion identifies the deterministic assembly
	// boundary without becoming part of the public request payload.
	ContextRetrievalPlanAssemblyVersion = "context-assembly-v1"

	contextRetrievalPlanExecutionPrefix = "context-execution-"
	contextRetrievalPlanRequestPrefix   = "context-request-"
)

var (
	// ErrInvalidContextRetrievalPlan identifies a malformed context request or
	// a plan that cannot safely be handed to retrieval.
	ErrInvalidContextRetrievalPlan = errors.New("query: invalid context retrieval plan")
	// ErrInvalidContextPlan is a concise compatibility alias.
	ErrInvalidContextPlan = ErrInvalidContextRetrievalPlan
)

// ContextRetrievalPlan is the immutable, deterministic retrieval input
// derived from one validated context request. IntentDigest binds the typed
// intent without exposing its text in either generated request identity.
type ContextRetrievalPlan struct {
	Input        QueryRetrievalInput
	IntentDigest string
}

// Validate checks the bounded retrieval input and the opaque identities
// generated by PlanContextRetrieval.
func (p ContextRetrievalPlan) Validate() error {
	if err := p.Input.Scope.Validate(); err != nil {
		return ErrInvalidContextRetrievalPlan
	}
	if p.Input.Limit < 1 || p.Input.Limit > retrieval.MaxTextSearchLimit {
		return ErrInvalidContextRetrievalPlan
	}
	if p.Input.QuestionKind != KnowledgeQuestionInventory && p.Input.QuestionKind != KnowledgeQuestionPossibleFlow ||
		!validContextText(p.Input.Question, maxContextQuestionBytes, true) ||
		!isSHA256(p.IntentDigest) {
		return ErrInvalidContextRetrievalPlan
	}
	if !validContextRetrievalPlanIdentity(p.Input.ExecutionID, contextRetrievalPlanExecutionPrefix) ||
		!validContextRetrievalPlanIdentity(p.Input.RequestID, contextRetrievalPlanRequestPrefix) {
		return ErrInvalidContextRetrievalPlan
	}
	if !strings.HasPrefix(p.Input.ExecutionID, contextRetrievalPlanExecutionPrefix) ||
		p.Input.ExecutionID[len(contextRetrievalPlanExecutionPrefix):] != p.Input.RequestID[len(contextRetrievalPlanRequestPrefix):] {
		return ErrInvalidContextRetrievalPlan
	}
	return nil
}

// PlanContextRetrieval validates a complete context request and projects its
// typed intent into the content-free retrieval input. It never mutates the
// request or includes raw question/target text in generated identities.
func PlanContextRetrieval(ctx context.Context, request ContextRequest, limit int) (ContextRetrievalPlan, error) {
	if ctx == nil {
		return ContextRetrievalPlan{}, ErrInvalidContextRetrievalPlan
	}
	if err := ctx.Err(); err != nil {
		return ContextRetrievalPlan{}, err
	}
	if err := request.Validate(); err != nil {
		return ContextRetrievalPlan{}, ErrInvalidContextRetrievalPlan
	}
	if limit < 1 || limit > retrieval.MaxTextSearchLimit {
		return ContextRetrievalPlan{}, ErrInvalidContextRetrievalPlan
	}

	question, questionKind := contextRetrievalPlanQuestion(request.Intent)
	intentDigest, err := contextRetrievalPlanIntentDigest(request.Intent)
	if err != nil {
		return ContextRetrievalPlan{}, ErrInvalidContextRetrievalPlan
	}
	identityDigest, err := contextRetrievalPlanIdentityDigest(request.Scope, request.Intent)
	if err != nil {
		return ContextRetrievalPlan{}, ErrInvalidContextRetrievalPlan
	}
	plan := ContextRetrievalPlan{
		Input: QueryRetrievalInput{
			ExecutionID:  contextRetrievalPlanExecutionPrefix + identityDigest,
			RequestID:    contextRetrievalPlanRequestPrefix + identityDigest,
			Question:     question,
			QuestionKind: questionKind,
			Scope:        request.Scope,
			Limit:        limit,
		},
		IntentDigest: intentDigest,
	}
	if err := plan.Validate(); err != nil {
		return ContextRetrievalPlan{}, ErrInvalidContextRetrievalPlan
	}
	if err := ctx.Err(); err != nil {
		return ContextRetrievalPlan{}, err
	}
	return plan, nil
}

func contextRetrievalPlanQuestion(intent Intent) (string, KnowledgeQuestionKind) {
	switch intent.Kind {
	case IntentKindQuestion:
		return intent.Question, KnowledgeQuestionInventory
	case IntentKindPossibleImpact:
		return intent.Target.ID, KnowledgeQuestionPossibleFlow
	case IntentKindEntity, IntentKindSymbol, IntentKindEvidenceInspection:
		return intent.Target.ID, KnowledgeQuestionInventory
	default:
		return "", ""
	}
}

type contextRetrievalPlanIdentityMaterial struct {
	Scope  Scope  `json:"scope"`
	Intent Intent `json:"intent"`
}

func contextRetrievalPlanIntentDigest(intent Intent) (string, error) {
	encoded, err := json.Marshal(intent)
	if err != nil {
		return "", err
	}
	digest := sha256.Sum256(encoded)
	return hex.EncodeToString(digest[:]), nil
}

func contextRetrievalPlanIdentityDigest(scope Scope, intent Intent) (string, error) {
	encoded, err := json.Marshal(contextRetrievalPlanIdentityMaterial{Scope: scope, Intent: intent})
	if err != nil {
		return "", err
	}
	digest := sha256.Sum256(encoded)
	return hex.EncodeToString(digest[:]), nil
}

func validContextRetrievalPlanIdentity(value, prefix string) bool {
	if !strings.HasPrefix(value, prefix) {
		return false
	}
	digest := value[len(prefix):]
	return isSHA256(digest) && validContextID(value)
}
